export const PROFILE_MIN_COMPLETION_PERCENT =
  Number(process.env.NEXT_PUBLIC_PROFILE_MIN_COMPLETION_PERCENT || '70');

export const PROFILE_COMPLETION_ENFORCED =
  process.env.NEXT_PUBLIC_PROFILE_COMPLETION_ENFORCED !== 'false';

